### ISSUE TITLE
ClassNotFound exception thrown when using EclipseLinkJPACacheStore with Push Replication

### ISSUE THREAD

**Issue by brianoliver** [coherence-community/coherence-incubator#133]
The following exception was encountered by Adam Niwczinski. It highlights a potential issue when running inside a container where by some existing classes aren't available on the classloader used by Coherence for Push Replication Classes.

The solution is to use the context classloader instead of the Coherence backing map classloader.

```
2015-03-19 22:05:59.821/40.772 Oracle Coherence GE 12.1.2.0.4 <Warning> (thread=DistributedCache:DistributedCacheWithPublishingCacheStore, member=1): Application code running on "DistributedCacheWithPublishingCacheStore" service thread(s) should not call ensureCache as this may result in deadlock. The most common case is a CacheFactory call from a custom CacheStore implementation.
2015-03-19 22:05:59.849/40.800 Oracle Coherence GE 12.1.2.0.4 <Error> (thread=DistributedCache:DistributedCacheForSubscriptions:EventDispatcher, member=1): Exception caught while dispatching to "<subscription-event-interceptor, com.oracle.coherence.common.liveobjects.LiveObjectEventInterceptor>": java.lang.RuntimeException: Failed to process event [StorageDispatcher$PartitionedCacheEntryEvent{Type=INSERTED, Service=DistributedCacheForSubscriptions, Cache=coherence.messagingpattern.subscriptions}] for LiveObject [CoherenceEventChannelSubscription{Subscription{subscriptionIdentifier=SubscriptionIdentifier{destinationIdentifier=Identifier{Site1-cluster:0x3DDB-MappointsOne}, subscriberIdentifier=Identifier{Site1:cluster:0x3DDB:MappointsOne:Cache Store Event Channel}}, status=ENABLED, visibleMessageTracker=DefaultMessageTracker{name=VisibleMessageTracker, lastPartitionId=0, ranges{}}}, distributorIdentifier=EventDistributor.Identifier{symbolicName=MappointsOne, externalName=Site1-cluster:0x3DDB-MappointsOne}, controllerIdentifier=EventChannelController.Identifier{symbolicName=Cache Store Event Channel, externalName=Site1:cluster:0x3DDB:MappointsOne:Cache Store Event Channel}, controllerDependencies=AbstractEventChannelController.Dependencies{channelName=Cache Store Event Channel, externalName=Site1:cluster:0x3DDB:MappointsOne:Cache Store Event Channel, eventChannelBuilder=com.oracle.coherence.patterns.eventdistribution.channels.CacheStoreEventChannelBuilder@4916610b, transformerBuilder=null, startingMode=ENABLED, batchDistributionDelayMS=1000, batchSize=100, restartDelay=10000, totalConsecutiveFailuresBeforeSuspended=-1, eventPollingDelay=1000}, cacheName=MappointsOne, resolver=com.tangosol.config.expression.ScopedParameterResolver@5c3d3ea9}]
at com.oracle.coherence.common.liveobjects.LiveObjectEventInterceptor.onEvent(LiveObjectEventInterceptor.java:215)
at com.tangosol.net.events.internal.NamedEventInterceptor.onEvent(NamedEventInterceptor.java:258)
at com.tangosol.net.events.internal.AbstractEvent.nextInterceptor(AbstractEvent.java:116)
at com.tangosol.net.events.internal.AbstractEvent.dispatch(AbstractEvent.java:154)
at com.tangosol.net.events.internal.AbstractEventDispatcher$4.proceed(AbstractEventDispatcher.java:270)
at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.PartitionedService$Continuations$Task.run(PartitionedService.CDB:6)
at com.tangosol.coherence.component.util.daemon.queueProcessor.Service$EventDispatcher.onNotify(Service.CDB:26)
at com.tangosol.coherence.component.util.Daemon.run(Daemon.CDB:51)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.oracle.coherence.common.liveobjects.LiveObjectEventInterceptor.onEvent(LiveObjectEventInterceptor.java:211)
... 8 more
Caused by: java.lang.NoClassDefFoundError: com/tangosol/net/cache/CacheStore
at java.lang.ClassLoader.findBootstrapClass(Native Method)
at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1070)
at java.lang.ClassLoader.loadClass(ClassLoader.java:414)
at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at com.tangosol.coherence.config.builder.InstanceBuilder.realize(InstanceBuilder.java:163)
at com.oracle.coherence.patterns.eventdistribution.channels.CacheStoreEventChannelBuilder.realize(CacheStoreEventChannelBuilder.java:86)
at com.oracle.coherence.patterns.eventdistribution.channels.CacheStoreEventChannelBuilder.realize(CacheStoreEventChannelBuilder.java:54)
at com.oracle.coherence.patterns.eventdistribution.distributors.AbstractEventChannelController.<init>(AbstractEventChannelController.java:428)
at com.oracle.coherence.patterns.eventdistribution.distributors.coherence.CoherenceEventChannelController.<init>(CoherenceEventChannelController.java:116)
at com.oracle.coherence.patterns.eventdistribution.distributors.coherence.CoherenceEventChannelSubscription$1.realize(CoherenceEventChannelSubscription.java:244)
at com.oracle.coherence.patterns.eventdistribution.distributors.EventChannelControllerManager.registerEventChannelController(EventChannelControllerManager.java:117)
at com.oracle.coherence.patterns.eventdistribution.distributors.coherence.CoherenceEventChannelSubscription.onEntryInserted(CoherenceEventChannelSubscription.java:234)
... 13 more

2015-03-19 22:05:59.879/40.830 Oracle Coherence GE 12.1.2.0.4 <Warning> (thread=DistributedCache:DistributedCacheForSubscriptions:EventDispatcher, member=1): The value of the attribute "EventChannelControllerState" for MBean "type=EventChannels,id=MappointsOne-Active1 Publisher,nodeId=1" could not be retrieved and is ignored; (Wrapped) java.lang.reflect.InvocationTargetException
2015-03-19 22:05:59.937/40.888 Oracle Coherence GE 12.1.2.0.4 <Warning> (thread=EventChannelController:Thread-5, member=1): <connect-timeout> as a child element of <tcp-initiator> is deprecated and will be removed in a future release; please use the <connect-timeout> element in <initiator-config> instead
2015-03-19 22:05:59.970/40.921 Oracle Coherence GE 12.1.2.0.4 <Error> (thread=DistributedCache:DistributedCacheForSubscriptions:EventDispatcher, member=1): Exception caught while dispatching to "<subscription-event-interceptor, com.oracle.coherence.common.liveobjects.LiveObjectEventInterceptor>": java.lang.RuntimeException: Failed to process event [StorageDispatcher$PartitionedCacheEntryEvent{Type=UPDATED, Service=DistributedCacheForSubscriptions, Cache=coherence.messagingpattern.subscriptions}] for LiveObject [CoherenceEventChannelSubscription{Subscription{subscriptionIdentifier=SubscriptionIdentifier{destinationIdentifier=Identifier{Site1-cluster:0x3DDB-MappointsOne}, subscriberIdentifier=Identifier{Site1:cluster:0x3DDB:MappointsOne:Cache Store Event Channel}}, status=ENABLED, visibleMessageTracker=DefaultMessageTracker{name=VisibleMessageTracker, lastPartitionId=38, ranges{38=RangeWrapper{partitionId=38, range=ContiguousRange[1]maxSequenceNumber=1}}}}, distributorIdentifier=EventDistributor.Identifier{symbolicName=MappointsOne, externalName=Site1-cluster:0x3DDB-MappointsOne}, controllerIdentifier=EventChannelController.Identifier{symbolicName=Cache Store Event Channel, externalName=Site1:cluster:0x3DDB:MappointsOne:Cache Store Event Channel}, controllerDependencies=AbstractEventChannelController.Dependencies{channelName=Cache Store Event Channel, externalName=Site1:cluster:0x3DDB:MappointsOne:Cache Store Event Channel, eventChannelBuilder=com.oracle.coherence.patterns.eventdistribution.channels.CacheStoreEventChannelBuilder@4269a448, transformerBuilder=null, startingMode=ENABLED, batchDistributionDelayMS=1000, batchSize=100, restartDelay=10000, totalConsecutiveFailuresBeforeSuspended=-1, eventPollingDelay=1000}, cacheName=MappointsOne, resolver=com.tangosol.config.expression.ScopedParameterResolver@25a09508}]
at com.oracle.coherence.common.liveobjects.LiveObjectEventInterceptor.onEvent(LiveObjectEventInterceptor.java:215)
at com.tangosol.net.events.internal.NamedEventInterceptor.onEvent(NamedEventInterceptor.java:258)
at com.tangosol.net.events.internal.AbstractEvent.nextInterceptor(AbstractEvent.java:116)
at com.tangosol.net.events.internal.AbstractEvent.dispatch(AbstractEvent.java:154)
at com.tangosol.net.events.internal.AbstractEventDispatcher$4.proceed(AbstractEventDispatcher.java:270)
at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.PartitionedService$Continuations$Task.run(PartitionedService.CDB:6)
at com.tangosol.coherence.component.util.daemon.queueProcessor.Service$EventDispatcher.onNotify(Service.CDB:26)
at com.tangosol.coherence.component.util.Daemon.run(Daemon.CDB:51)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.oracle.coherence.common.liveobjects.LiveObjectEventInterceptor.onEvent(LiveObjectEventInterceptor.java:211)
... 8 more
Caused by: java.lang.NullPointerException
at com.oracle.coherence.patterns.eventdistribution.distributors.coherence.CoherenceEventChannelSubscription.onEntryUpdated(CoherenceEventChannelSubscription.java:283)
... 13 more
```

**Comment by yashwanthmadaka24** [comment]
Hey, I ran into the same problem.
I cannot see any solution which you have implemented for this issue. 
where can I refer the solution?
